[project]
name = "brus_backend_common"
version = "0.0.1"
authors = [
  {name = "fedspendingtransparency"},
]
description = "A shared package of scripts, models, and libraries to be shared across fedspendingtransparency repos"
readme = 'README.md'
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.black]
line-length = 120
target-version = ['py312']
exclude = '/(\.git|\.venv|venv|migrations)/'

[tool.coverage.run]
omit = [
    # tests themselves don't need coverage measurements
    "*/tests/*",
    # nor db migration scripts
    "*/migrations/*",
]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover"
]
