name: Initialize Test Environment

inputs:
  is-integration-test:
    description: Triggers build steps needed to support integration tests
    required: true
  is-spark-test:
    description: Triggers build steps needed to support tests that utilize Spark
    required: true
  working-directory:
    description: Directory where the requirements can be found; used when multiple repos are checked out
    default: ""

runs:
  using: composite
  steps:
    - name: Set combined ENV
      shell: bash
      # MINIO_HOST check will be localhost cause we're still outside the docker containers
      run: |
        echo "MINIO_DATA_DIR=$HOME/Development/data/brus-backend-common/docker/brus-backend-common-s3" >> $GITHUB_ENV
        echo "MINIO_HOST=localhost" >> $GITHUB_ENV

#    # The conditionals below this all check against a string because inputs for actions are actually
#    # strings, not booleans: https://github.com/actions/runner/issues/1483
#    - name: Create directories needed for Minio
#      if: ${{ inputs.is-integration-test == 'true' }}
#      shell: bash
#      run: mkdir -p "$MINIO_DATA_DIR"

#    - name: Build docker containers for Minio
#      working-directory: ${{ inputs.working-directory }}
#      if: ${{ inputs.is-integration-test == 'true' }}
#      shell: bash
#      run: docker compose up -d minio

#    - name: Create directories needed for Spark
#      if: ${{ inputs.is-spark-test == 'true' }}
#      shell: bash
#      run: mkdir -p "$HOME/.ivy2"

#    - name: Download docker image
#      if: ${{ inputs.is-spark-test == 'true' }}
#      uses: actions/download-artifact@v4
#      with:
#        name: brus-backend-common
#        path: /tmp

#    - name: Load docker image
#      shell: bash
#      if: ${{ inputs.is-spark-test == 'true' }}
#      run: docker load --input /tmp/brus-backend-common.tar

#    - name: Build docker containers for Minio
#      working-directory: ${{ inputs.working-directory }}
#      if: ${{ inputs.is-spark-test == 'true' }}
#      shell: bash
#      run: docker compose up -d brus-backend-common

#    - name: Capture SPARK_HOME environment variable
#      if: ${{ inputs.is-spark-test == 'true' }}
#      shell: bash
#      run: echo "SPARK_HOME=$(python -c "import site;print(f'{site.getsitepackages()[0]}/pyspark')")" >> $GITHUB_ENV
#
#    - name: install basic jars
#      if: ${{ inputs.is-spark-test == 'true' }}
#      shell: bash
#      run: >
#        pyspark --packages
#        "org.apache.hadoop:hadoop-aws:$HADOOP_VERSION,io.delta:delta-spark_$SCALA_VERSION:$DELTA_VERSION,org.apache.spark:spark-hive_$SCALA_VERSION:$SPARK_VERSION"

    # Have to do this again as its a separate job
    - name: Build test .env off .env.template
      shell: bash
      run: cp ./brus-backend-common/.github/.env.test .env

#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v3

#    - name: Use cached image in test job
#      uses: docker/bake-action@v7
#      with:
#        targets: brus-backend-common
#        set: |
#          brus-backend-common.cache-from=type=gha
#        load: true

    - name: Download docker image
      if: ${{ inputs.is-integration-test == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: brus-backend-common
        path: /tmp

    - name: Load docker image
      shell: bash
      if: ${{ inputs.is-integration-test == 'true' }}
      run: docker image import /tmp/brus-backend-common.tar brus-backend-common:latest

    - name: Run services with Docker Compose
      if: ${{ inputs.is-integration-test == 'true' }}
      uses: hoverkraft-tech/compose-action@v2.5.0
      with:
        compose-file: ./brus-backend-common/docker-compose.yml
        # Use --no-build as the images are already built by the bake action
        up-flags: 'brus-backend-common minio --no-build'


    - name: Wait on minio container to be available
      if: ${{ inputs.is-integration-test == 'true' }}
      shell: bash
      run: |
        ttl=30; echo "Try minio conn from container for $ttl seconds"; until [ $ttl -le 0 ] || curl $MINIO_HOST:10002; do echo $ttl; ((ttl--)); sleep 1; done; [ $ttl -gt 0 ]