name: Unit Tests

on:
  workflow_call:

jobs:
  Run:
    name: Run
    runs-on: ${{ vars.RUNNER_VERSION }}
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          path: brus-backend-common
#
#      - name: Init Python Environment
#        uses: ./brus-backend-common/.github/actions/init-python-environment
#        with:
#          working-directory: ./brus-backend-common

      - name: Init Test Environment
        uses: ./brus-backend-common/.github/actions/init-test-environment
        with:
          is-integration-test: false
          is-spark-test: false
          working-directory: ./brus-backend-common

      - name: Run Test Cases
        id: run-test-cases
        uses: ./brus-backend-common/.github/actions/run-pytest
        with:
          cov-report-name: 'unit-tests'
          ignore-glob: '**/tests/integration/*'
          include-glob: 'test_*.py *_test.py'
          marker: '(not signal_handling)'
          working-directory: ./brus-backend-common
          container: 'brus-backend-common'
