name: Non-Spark Integration Tests

on:
  workflow_call:

defaults:
  run:
    working-directory: brus-backend-common

jobs:

  Run:
    name: Run
    runs-on: ${{ vars.RUNNER_VERSION }}
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          path: brus-backend-common

      - name: Init Python Environment
        uses: ./brus-backend-common/.github/actions/init-python-environment
        with:
          working-directory: ./brus-backend-common

      - name: Init Test Environment
        uses: ./brus-backend-common/.github/actions/init-test-environment
        with:
          is-integration-test: true
          is-spark-test: false
          working-directory: ./brus-backend-common

      - name: Run Test Cases
        uses: ./brus-backend-common/.github/actions/run-pytest
        with:
          cov-report-name: 'non-spark-integration-tests'
          include-glob: '**/tests/integration/*'
          marker: '(not signal_handling and not spark)'
          num-processes: 0
          working-directory: ./brus-backend-common
